import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./graphik-font/graphik-font.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import { notFound } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const locales = ["en", "ar"];
export default function RootLayout({ children, params: { locale } }: any) {
  if (!locales.includes(locale as any)) notFound();
  return (
    <html lang={locale}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
